spring.application.name=GlobalHousing

spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${DB_USERNAME:JOELADMIN}
spring.datasource.password=${DB_PASSWORD:changeme}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com


# properties
# IMPORTANT: use a secret of at least 32 bytes (256 bits) for HMAC-SHA algorithms
app.jwt.secret=${JWT_SECRET:Y7g9uK3rH2pL8vQ0sDf5Wx1Zb7Nn4Mm8}
app.jwt.expiration-ms=3600000
app.frontend.url=http://localhost:4200/auth/success